### ISSUE TITLE
Can you please share the assets through onedrive or my email?

### ISSUE THREAD

**Issue by Taoismer** [Sim-on-Wheels/Sim-on-wheels-Renderer#1]

**Comment by yshen47** [comment]
Hello there,

Yeah, let us prepare a one drive version. 

Best,
Yuan

**Comment by yshen47** [comment]
Here is the one drive link, https://1drv.ms/f/s!AvOiKE0vFTuWik9ciMHq_pIxyD3T?e=tA2B8j, hope it helps!
