### ISSUE TITLE
about the run sim-on-wheels renderer on real-world ROSBAG sequences

### ISSUE THREAD

**Issue by rockywind** [Sim-on-Wheels/Sim-on-wheels-Renderer#3]
Hi, thank you for sharing your great work.
When I run the ```` CUDA_VISIBLE_DEVICES=1 xvfb-run --auto-servernum --server-num=1  python main_my.py````  the result is always stuck in below.
![image](https://github.com/Sim-on-Wheels/Sim-on-wheels-Renderer/assets/14838781/126cec9e-ed89-4756-8698-3f1edcf3a8b0)
The config is below.
![image](https://github.com/Sim-on-Wheels/Sim-on-wheels-Renderer/assets/14838781/6d7cae8e-0c26-4253-9739-353c8c24303e)

**Comment by yshen47** [comment]
Hi there, just to check, are you able to see the pygame window?

**Comment by rockywind** [comment]
Hi, I ran it in the server so I can' see the pygame windows.

**Comment by yshen47** [comment]
I am not sure about the issue above on why it stuck around those frames for you. On my side, it runs the ROS sequence following 8-shape trajectory. Is the previous 690 frames running fine with composited pedestrian animation for you?  Without the pygame window opening, I remember it's possible for you to dump the frames if uncommenting line 154 to line 157 in main.py. I haven't tried os without GUI display, so not very sure the behavior in those setting

**Comment by rockywind** [comment]
Thanks a lot. I have a try.
